export const SET_MERCHANT = "SET_MERCHANT";
export const LOGOUT_MERCHANT = "LOGOUT_MERCHANT";
export const RESET_PASSWORD_EMAIL_SENT_MESSAGE = "RESET_PASSWORD_EMAIL_SENT_MESSAGE"
export const RESET_PASSWORD = "RESET_PASSWORD"
export const RESET_PASSWORD_SET = "RESET_PASSWORD_SET"